### ISSUE TITLE
MAKERphone_border.stl is missing

### ISSUE THREAD

**Issue by steka** [RussNelson/ringo#1]
The `case.scad` file imports `MAKERphone_border.stl`, but it seems you forgot to add the file to the repository.

Opening `case.scad` with OpenSCAD report:
**`WARNING: Can't open import file '/home/nelson/ringo/MAKERphone_border.stl', import() at line 20`**

**Comment by RussNelson** [comment]
Fixed, thanks!

**Comment by steka** [comment]
Sorry, but it seems that you forgot to push the changes to GitHub.

**Comment by RussNelson** [comment]
Exactly what happened, yes! I got distracted by Github's change in RSA
keys. Thank for the reminder.

Writing objects: 100% (3/3), 6.09 KiB | 6.09 MiB/s, done.
Total 3 (delta 0), reused 0 (delta 0)
To github.com:RussNelson/ringo.git
   93ea912..ceaf8a3  master -> master

**Comment by steka** [comment]
Thanks, now we have the file.
I was however forced to modify the path to it in `case.scad` to make it work.

I recommend the following changes:
![image](https://github.com/RussNelson/ringo/assets/2719766/7aab98a3-73c7-41e0-9dd0-f7208fbe600d)
